server:
  port: 8030

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:1001/eureka/ #eureka服务注册地址

# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springdate/aigou.git #git仓库地址
          searchPaths: config* #搜索路径
          username: 207416530@qq.com
          password: wasdWASD8
  application:
    name: aigou-config-server