server:
  port: 8030

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/ #eureka服务注册地址

# git管理配置
spring:
  application:
    name: aigou-config-server
    #配置文件所在的分支
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springdate/aigou.git #git仓库地址
          search-paths: aigou_parent/aigou_config_server/src/main/resources/config #搜索路径
          username: 207416530@qq.com
          password: wasdWASD8
      label: master