server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/ #eureka服务注册地址
spring:
  application:
    name: aigou-user-server
user:
  id: ${port}
  userName: ${ip}