#spring   jdbc:mysql://123.57.205.36:3306/zyyq ECPCinsea      jdbc:mysql://localhost:3306/test  ?characterEncoding=UTF-8&useUnicode=true&useSSL=false
spring:
  datasource:
    url: ${db-url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db-username}
    password: ${db-password}