#spring   jdbc:mysql://123.57.205.36:3306/zyyq ECPCinsea      jdbc:mysql://localhost:3306/test  ?characterEncoding=UTF-8&useUnicode=true&useSSL=false
spring:
  datasource:
    url: ${db-url}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${db-username}
    password: ${db-password}

logging:
  path: /opt/logs/dev
  level:
    com:
      mcrt:
        zyzwzx: debug